[package]
name = "ticket_booth_contract"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.4.0"
# openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }
# game_components_token = { git = "https://github.com/Provable-Games/game-components.git", branch = "feat/ticket-booth", submodules = ["packages/token"] }
# game_components_metagame = { git = "https://github.com/Provable-Games/game-components.git", branch = "feat/ticket-booth", submodules = ["packages/metagame"] }
# death_mountain = { git = "https://github.com/Provable-Games/death-mountain.git", branch = "feat/beast-mode" }
# beasts = { git = "https://github.com/Provable-Games/beasts.git", branch = "main" }

[[target.starknet-contract]] 